-- Q1. What is the total revenue generated by male vs. female customers?
SELECT GENDER, SUM(purchase_amount) AS REVENUE
FROM customer_behavior_cleaned
GROUP BY GENDER;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id,purchase_amount , (SELECT AVG(purchase_amount) FROM customer_behavior_cleaned WHERE discount_applied='Yes') 
AS AVG_Purchase_Amount 
FROM customer_behavior_cleaned
WHERE discount_applied='Yes' AND purchase_amount>=(SELECT AVG(purchase_amount) FROM customer_behavior_cleaned WHERE discount_applied='Yes');

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased,ROUND(AVG(review_rating),2)  AS avg_review_rating FROM customer_behavior_cleaned 
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT ROUND(AVG(purchase_amount),2), shipping_type FROM customer_behavior_cleaned
WHERE shipping_type in ('Standard','Express')
group by shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT COUNT(customer_id) AS total_customer ,
ROUND(AVG(purchase_amount),2) AS avg_purchase_amount,
 ROUND(SUM(purchase_amount),2) AS total_revenue 
 FROM customer_behavior_cleaned
group by subscription_status
order by total_revenue DESC;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased, ROUND(100.0* SUM( CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END )/COUNT(*),2) AS discount_rate
FROM customer_behavior_cleaned
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
WITH customer_type AS (SELECT customer_id, previous_purchases,
 CASE
 WHEN previous_purchases=1 THEN 'NEW CUSTOMER'
 WHEN previous_purchases BETWEEN 2 AND 10 THEN 'RETURNING'
 ELSE 'LOYAL'
 END AS customer_segment
 FROM customer_behavior_cleaned)
 
 SELECT customer_segment,COUNT(*) AS Number_of_Customers
 FROM customer_type
 GROUP BY customer_segment;
 
 -- Q8. What are the top 3 most purchased products within each category? 
 WITH item_counts AS (SELECT category ,item_purchased,
 COUNT(customer_id) AS total_orders,
 ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
 FROM customer_behavior_cleaned
 GROUP BY category,item_purchased)
 
 SELECT item_rank,total_orders, category, item_purchased
 FROM item_counts
 WHERE item_rank<=3;
 
 -- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
 SELECT subscription_status, COUNT(customer_id) AS repeat_buyers FROM customer_behavior_cleaned
 WHERE previous_purchases>5 
 GROUP BY subscription_status;
 
 -- Q10. What is the revenue contribution of each age group?
 SELECT age_group , SUM(purchase_amount) AS total_revenue FROM customer_behavior_cleaned
 GROUP BY age_group
 ORDER BY total_revenue DESC;
 